<!doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
          integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <title>BMI</title>
</head>
<body>

<!--This alligns the 'fields' within the closing tag </div> to the center of the page-->
<!-- everything within this tag is the visual bmi page -->
<div class="container">
    <!--"img-fluid" makes the pic responsive. "mb-4" creates a bottom margin of 4px (space under pic)-->
    <img src="images/bmi.png" class="img-fluid mb-4">